export const projects = [
  {
    number: "01",
    name: "Lernio AI",
    short: "Lernio",
    kind: "Adaptive learning operating system",
    summary: "AI woven into the whole learning flow—not attached as a decorative chat box.",
    detail:
      "LEO tutoring, quizzes, spaced repetition, planning, analytics, coding labs, community, and role-aware learning workflows in one system.",
    proof: ["44 subjects", "241 lessons", "80+ API routes", "Live product"],
    stack: ["Next.js", "React", "PostgreSQL", "Groq"],
    media: "/assets/lernio-screenshot.jpg",
    status: "Live",
    color: "#9b7cff",
    live: "https://lernioai.vercel.app",
    repo: "https://github.com/GYASH28/LERNIOAI",
  },
  {
    number: "02",
    name: "B.R.A.C.E",
    short: "Brace",
    kind: "Permissioned desktop AI companion",
    summary: "A local-first assistant built around memory, tools, voice, and visible user control.",
    detail:
      "Model routing, approval gates, persistent context, voice states, browser tools, terminal actions, file access, and MCP integrations without hiding risky handoffs.",
    proof: ["Local-first", "Tool approvals", "Persistent memory", "Voice states"],
    stack: ["Electron", "React", "TypeScript", "Node.js"],
    media: null,
    status: "Active R&D",
    color: "#19c9ff",
    repo: "https://github.com/GYASH28/brace_new",
  },
  {
    number: "03",
    name: "CampusMate",
    short: "Campus",
    kind: "Multi-role campus platform",
    summary: "A college operations layer shaped around the responsibilities of every campus role.",
    detail:
      "Attendance, notices, timetables, assignments, notes, examinations, QR workflows, analytics, and PWA behaviour for students and staff.",
    proof: ["5 user roles", "QR attendance", "PWA", "Live deployment"],
    stack: ["React", "Vite", "Firebase", "Recharts"],
    media: null,
    status: "Live",
    color: "#e6ff35",
    live: "https://campuscwit.vercel.app",
    repo: "https://github.com/GYASH28/CAMPUSMATE",
  },
  {
    number: "04",
    name: "Fakhri Mart",
    short: "Fakhri",
    kind: "Wholesale catalogue experience",
    summary: "A product discovery and enquiry system for a traditional yarn business moving online.",
    detail:
      "A cinematic brand introduction, catalogue storytelling, product filtering, mobile-first discovery, and direct WhatsApp enquiry flows.",
    proof: ["Client project", "Product filters", "WhatsApp flow", "Motion-led UI"],
    stack: ["React", "Vite", "GSAP", "Vercel"],
    media: null,
    status: "Client build",
    color: "#ff995f",
    repo: "https://github.com/GYASH28/sample-website",
  },
  {
    number: "05",
    name: "Cinematic Portfolio",
    short: "Portfolio",
    kind: "Motion-led personal experience",
    summary: "A web experience where identity, motion, and frontend engineering share the frame.",
    detail:
      "Scroll choreography, layered portrait scenes, project storytelling, tactile interactions, and responsive motion composed as a single narrative.",
    proof: ["Scroll narrative", "3D experiments", "Responsive motion", "Public build"],
    stack: ["React", "GSAP", "Three.js", "Vercel"],
    media: null,
    status: "Public build",
    color: "#f3eee4",
    repo: "https://github.com/GYASH28/YASH_PORTFOLIO",
  },
  {
    number: "06",
    name: "Interactive Quiz",
    short: "Quiz",
    kind: "Focused browser experiment",
    summary: "A compact, zero-framework quiz using the simplest stack the problem required.",
    detail:
      "Dynamic questions, immediate scoring, clear feedback, keyboard-friendly interaction, and responsive behaviour in plain web technology.",
    proof: ["Zero framework", "Instant scoring", "Responsive", "GitHub Pages"],
    stack: ["HTML", "CSS", "JavaScript"],
    media: null,
    status: "Live",
    color: "#6fffd0",
    live: "https://gyash28.github.io/WD_practical_no_20/",
    repo: "https://github.com/GYASH28/WD_practical_no_20",
  },
];

export const labs = [
  {
    id: "operations",
    label: "Operations",
    title: "Remove repetitive work without replacing the people who understand it.",
    copy: "Map the current process, expose the expensive friction, then build a narrow automation layer around the tools the team already trusts.",
    input: "Repeated handoffs",
    engine: "Rules + AI reasoning",
    output: "A faster, visible workflow",
  },
  {
    id: "knowledge",
    label: "Knowledge",
    title: "Turn scattered company information into answers people can verify.",
    copy: "Design a source-aware knowledge system where retrieval, permissions, citations, and human escalation are part of the product—not afterthoughts.",
    input: "Docs, notes, files",
    engine: "Search + retrieval",
    output: "Grounded answers",
  },
  {
    id: "customer",
    label: "Customer",
    title: "Respond quickly while keeping a clean path back to a real person.",
    copy: "Build assisted lead capture, support, and enquiry journeys that are fast, contextual, and honest about where automation stops.",
    input: "Customer questions",
    engine: "Intent + context",
    output: "Helpful responses",
  },
  {
    id: "product",
    label: "Product",
    title: "Move an AI idea from a slide deck into a contained, testable pilot.",
    copy: "Combine product scope, interface design, model choices, integrations, and deployment into one accountable build loop.",
    input: "A valuable use case",
    engine: "Prototype + test",
    output: "A working pilot",
  },
];

export const process = [
  ["Discover", "Understand the users, workflow, information, and outcome worth changing."],
  ["Frame", "Define boundaries, permissions, failure modes, and the smallest useful promise."],
  ["Prototype", "Build a tactile core quickly enough to learn from real use instead of assumptions."],
  ["Pressure-test", "Test edge cases, handoffs, mobile behaviour, and the places automation should stop."],
  ["Deploy", "Ship with documentation, ownership, observability, and a clear improvement loop."],
];

export const faqs = [
  ["What does AI implementation include?", "Workflow discovery, product scope, interface design, model and tool selection, integrations, automation, permissions, testing, deployment, documentation, and handover—depending on what the workflow actually needs."],
  ["Can you work with a small company?", "Yes. A small company often gets more value from one tightly chosen workflow than from a broad and expensive AI programme."],
  ["How do you work with a larger organization?", "I begin with a contained pilot and the relevant product, operations, or IT stakeholders. Roles, access, approvals, existing systems, and rollout constraints are made explicit before the scope grows."],
  ["Will this replace our current software?", "Usually not at first. The better starting question is whether AI can improve the tools and process already in place. A standalone tool only makes sense when integration would create more friction than value."],
  ["Which models and platforms do you use?", "I choose the stack around the job. My project work includes Gemini, Groq, local providers, n8n, Firebase, PostgreSQL, React, Next.js, Electron, and modern deployment platforms."],
  ["How do you approach privacy and control?", "Minimum necessary access, explicit user permissions, visible approval points, source traceability, and a deployment model appropriate to the sensitivity of the work."],
];

