import {chromium} from 'playwright';import fs from 'node:fs/promises';
const base=process.env.BASE_URL||'http://127.0.0.1:4173';await fs.mkdir('qa-v13',{recursive:true});const browser=await chromium.launch({headless:true});const failures=[],notes=[];const fail=(scope,msg,extra={})=>failures.push({scope,msg,...extra});
const sizes=[['desktop',1440,900],['tablet',820,1100],['mobile',390,844]];
for(const [name,width,height] of sizes){
 const c=await browser.newContext({viewport:{width,height},deviceScaleFactor:1,reducedMotion:'no-preference'});const p=await c.newPage();const errs=[];p.on('console',m=>{if(m.type()==='error')errs.push(m.text())});p.on('pageerror',e=>errs.push(e.message));
 let r=await p.goto(base+'/index.html',{waitUntil:'networkidle',timeout:90000});if(!r?.ok())fail(name,'homepage not 2xx',{status:r?.status()});await p.waitForTimeout(800);
 const basics=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,heroH:document.querySelector('.hero')?.getBoundingClientRect().height,styles:[...document.styleSheets].map(s=>s.href).filter(Boolean),scripts:[...document.scripts].map(s=>s.src).filter(Boolean),heroName:getComputedStyle(document.querySelector('.hero-name')).zIndex,heroFront:getComputedStyle(document.querySelector('.hero-front')).zIndex,heroBg:getComputedStyle(document.querySelector('.hero-bg')).backgroundImage}));notes.push({name,basics:{...basics,heroBg:basics.heroBg.slice(0,48)}});
 if(basics.overflow>2)fail(name,'homepage horizontal overflow',basics);if(basics.heroH<height*.9)fail(name,'hero too short',basics);if(!basics.styles.some(x=>x.includes('v13.css')))fail(name,'v13.css missing');if(!basics.styles.some(x=>x.includes('v13-hero-image.css')))fail(name,'embedded hero stylesheet missing',basics);if(basics.styles.some(x=>/v10|v11|v12\.css/.test(x)))fail(name,'legacy CSS loaded',basics);if(!basics.scripts.some(x=>x.includes('v13.js')))fail(name,'v13.js missing');if(Number(basics.heroFront)<=Number(basics.heroName))fail(name,'portrait is not layered above background name',basics);if(!basics.heroBg.startsWith('url("data:image/webp;base64,'))fail(name,'hero is not using embedded WebP', {heroBg:basics.heroBg.slice(0,80)});
 const heroAsset=await p.evaluate(async()=>{const css=getComputedStyle(document.querySelector('.hero-bg')).backgroundImage;const m=css.match(/^url\(["']?(data:image\/webp;base64,[^"')]+)["']?\)$/);if(!m)return{w:0,h:0,matched:false};const img=new Image();img.src=m[1];await img.decode();return{w:img.naturalWidth,h:img.naturalHeight,matched:true}});if(heroAsset.w!==3840||heroAsset.h!==2160)fail(name,'embedded hero is not 3840×2160',heroAsset);await p.screenshot({path:`qa-v13/${name}-home-hero.png`});
 await p.locator('#plans').scrollIntoViewIfNeeded();await p.waitForTimeout(260);await p.locator('[data-plan-mode="once"]').click();await p.waitForTimeout(120);const oneTimeVisible=await p.locator('[data-plan-model="once"]:visible').count();const managedVisible=await p.locator('[data-plan-model="managed"]:visible').count();if(oneTimeVisible!==3||managedVisible!==0)fail(name,'plan mode switching incorrect',{oneTimeVisible,managedVisible});await p.screenshot({path:`qa-v13/${name}-plans.png`});
 const workHref=await p.locator('.feature-card').getAttribute('href');if(!workHref?.includes('work.html'))fail(name,'client work teaser does not open dedicated page',{workHref});await p.locator('.nav-cta').click();await p.waitForTimeout(100);if(!(await p.locator('#enquiryDialog').evaluate(el=>el.open)))fail(name,'homepage enquiry dialog did not open');await p.locator('[data-close-dialog]').click();
 r=await p.goto(base+'/work.html',{waitUntil:'networkidle',timeout:90000});if(!r?.ok())fail(name,'work page not 2xx',{status:r?.status()});await p.waitForTimeout(550);const workBasics=await p.evaluate(()=>({overflow:document.documentElement.scrollWidth-document.documentElement.clientWidth,tabs:document.querySelectorAll('[data-journey]').length,title:document.title}));if(workBasics.overflow>2)fail(name,'work page horizontal overflow',workBasics);if(workBasics.tabs!==5)fail(name,'journey tab count wrong',workBasics);await p.screenshot({path:`qa-v13/${name}-work-hero.png`});
 await p.locator('.journey').scrollIntoViewIfNeeded();await p.waitForTimeout(300);for(let i=0;i<5;i++){await p.locator('[data-journey]').nth(i).click();await p.waitForTimeout(500);const info=await p.locator('#journeyImage').evaluate(el=>({src:el.getAttribute('src'),complete:el.complete,w:el.naturalWidth,h:el.naturalHeight,opacity:getComputedStyle(el).opacity}));if(!info.complete||!info.w||!info.h||info.opacity==='0')fail(`${name}/journey-${i}`,'journey image invalid',info)}await p.screenshot({path:`qa-v13/${name}-work-journey.png`});
 await p.locator('.nav-cta').click();await p.waitForTimeout(80);if(!(await p.locator('#enquiryDialog').evaluate(el=>el.open)))fail(name,'work enquiry dialog did not open');await p.locator('[data-close-dialog]').click();if(errs.length)fail(name,'browser errors',{errs});await c.close();
}
const c=await browser.newContext({viewport:{width:1280,height:800},reducedMotion:'reduce'});const p=await c.newPage();await p.goto(base+'/index.html',{waitUntil:'networkidle',timeout:90000});await p.waitForTimeout(350);const reduced=await p.evaluate(()=>({reveal:getComputedStyle(document.querySelector('.reveal')).transform,cursor:getComputedStyle(document.querySelector('.cursor-light')).display}));if(reduced.reveal!=='none')fail('reduced-motion','reveal transform still active',reduced);if(reduced.cursor!=='none')fail('reduced-motion','cursor light still active',reduced);await c.close();await browser.close();
const report={generatedAt:new Date().toISOString(),failures,notes};await fs.writeFile('qa-v13/report.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(failures.length)process.exit(1);
